name: Daily Slack Ping

on:
  schedule:
    - cron: '0 9 * * *'  # Runs daily at 9:00 UTC
  workflow_dispatch:     # Allow manual triggering

permissions:
  contents: write

jobs:
  slack-ping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily Slack ping
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          python ping.py

      - name: Commit updated state
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "SlackBot"
          git add state.json
          git commit -m "Update state.json for next ping" || echo "No changes to commit"
          git push
